### ISSUE TITLE
CSS support

### ISSUE THREAD

**Issue by michail-vestnik** [JoaoDanielRufino/gcloc#22]
Hi!

Greet work!
How about CSS?

**Comment by JoaoDanielRufino** [comment]
Hi @michail-vestnik , thanks!!

GCloc already supports CSS, you can install the latest version of it by clicking [here](https://github.com/JoaoDanielRufino/gcloc/releases/latest) or you can update your docker image to use the latest version: `docker pull joaodanielrufino/gcloc:latest`

**Comment by michail-vestnik** [comment]
Thanks!!!
