### ISSUE TITLE
Add python code sample for tests

### ISSUE THREAD

**Issue by JoaoDanielRufino** [JoaoDanielRufino/gcloc#24]
Add python code samples for tests on analyzer and scanner

**Comment by WaniAthar** [comment]
hey @JoaoDanielRufino can i work on this issue?

**Comment by JoaoDanielRufino** [comment]
> hey @JoaoDanielRufino can i work on this issue?

Sure :)

**Comment by WaniAthar** [comment]
assign me this issue

**Comment by JoaoDanielRufino** [comment]
> assign me this issue

Are you still plan to do this issue ?

**Comment by kalpitshah2311** [comment]
Can you please assign this issue to me? I wanna contribute

**Comment by Lionzee** [comment]
Im doin this one, can you check my PR?
Thank you so much,
