### ISSUE TITLE
Add java code sample for tests

### ISSUE THREAD

**Issue by JoaoDanielRufino** [JoaoDanielRufino/gcloc#27]
Add java code samples for tests on analyzer and scanner

**Comment by anirudh0806** [comment]
could you please elaborate on what you need exactly?

**Comment by amoghrajesh** [comment]
@JoaoDanielRufino is this issue still open? I want to take it up

**Comment by JoaoDanielRufino** [comment]
> @JoaoDanielRufino is this issue still open? I want to take it up

Yes, take it!
