### ISSUE TITLE
Add markdown code sample for tests

### ISSUE THREAD

**Issue by JoaoDanielRufino** [JoaoDanielRufino/gcloc#39]
Add markdown code samples for tests on analyzer and scanner

**Comment by hardiksachan** [comment]
Hey there, I'd like to work on this

**Comment by JoaoDanielRufino** [comment]
> Hey there, I'd like to work on this

You have 5 days to work on this, otherwise I will unassign you

**Comment by JoaoDanielRufino** [comment]
@hardiksachan I will unassign you due inactivity

**Comment by bitethecode** [comment]
@JoaoDanielRufino Could I also take this?

**Comment by JoaoDanielRufino** [comment]
> @JoaoDanielRufino Could I also take this?

Yes, you have 5 days or I will unassign you

**Comment by bitethecode** [comment]
@JoaoDanielRufino Np!

**Comment by JoaoDanielRufino** [comment]
Closes due PR #57
