### ISSUE TITLE
Add Makefile code sample for tests

### ISSUE THREAD

**Issue by JoaoDanielRufino** [JoaoDanielRufino/gcloc#51]
Add Makefile code samples for tests on analyzer and scanner

**Comment by sobczak-m** [comment]
Could you describe in more detail what is to be done?

`make analyzer-test` for run tests in pkg/analyzer and same behaviour for scanner?

**Comment by bitethecode** [comment]
Could you assign this to me? I love to work on this :)

**Comment by JoaoDanielRufino** [comment]
> Could you describe in more detail what is to be done?
> 
> `make analyzer-test` for run tests in pkg/analyzer and same behaviour for scanner?

Look at this [PR](https://github.com/JoaoDanielRufino/gcloc/pull/46). Basically you need to add a Makefile sample code on `test/fixtures/code_samples` and then update `analyzer_test.go` and `scanner_test.go`

**Comment by JoaoDanielRufino** [comment]
> @JoaoDanielRufino Could you assign this to me? I love to work on this :)

I will assign you and @sobczak-m , the one who do it first you be accepted

**Comment by bitethecode** [comment]
@JoaoDanielRufino sounds good. I will put up pr tomorrow

**Comment by bitethecode** [comment]
@JoaoDanielRufino I made a pull request for this. Please review it when you have a chance!

**Comment by JoaoDanielRufino** [comment]
Close due PR #56
