### ISSUE TITLE
Add Plain Text code sample for tests

### ISSUE THREAD

**Issue by JoaoDanielRufino** [JoaoDanielRufino/gcloc#59]
Add Plain Text code samples for tests on analyzer and scanner

**Comment by Tashima42** [comment]
E ae, @JoaoDanielRufino 

The samples need to be added to this folder? https://github.com/JoaoDanielRufino/gcloc/tree/master/test/fixtures/code_samples

Do you prefer `.txt` files or no extension at all?

Thanks!

**Comment by JoaoDanielRufino** [comment]
> E ae, @JoaoDanielRufino
> 
> The samples need to be added to this folder? https://github.com/JoaoDanielRufino/gcloc/tree/master/test/fixtures/code_samples
> 
> Do you prefer `.txt` files or no extension at all?
> 
> Thanks!

Yes, on that folder!

You could use the `.txt.` extension, thanks.

You have 5 days to work on this, owtherwise I will unassign you
