### ISSUE TITLE
Go version upgrade

### ISSUE THREAD

**Issue by misantron** [JoaoDanielRufino/gcloc#65]
Go team officially maintains two last versions of language.
The current version is 1.19. The current version here is 1.17.
May be it's time for upgrade?
What do yo think about it?
Thanks.

**Comment by JoaoDanielRufino** [comment]
> Go team officially maintains two last versions of language. The current version is 1.19. The current version here is 1.17. May be it's time for upgrade? What do yo think about it? Thanks.

Hi @misantron, thanks for the suggestion.

For now, I plan to keep the current version, later I will test everything and upgrade it by my self.

I will close this issue because I want to do it my self.
