### ISSUE TITLE
Is it possible to analyze private github repositories?

### ISSUE THREAD

**Issue by colussim** [JoaoDanielRufino/gcloc#68]
Is it possible to analyze private github repositories with parameters : user , token or only token ?

**Comment by JoaoDanielRufino** [comment]
Hi @colussim,

To download the files and github repositores, I use [go-getter](https://github.com/hashicorp/go-getter) package and by looking at their [readme](https://github.com/hashicorp/go-getter#git-git), it seems that it's possible to analyze private github repositores either via ssh key or https protocol

**Comment by colussim** [comment]
Hi @JoaoDanielRufino ,
With ssh-key it is ok but with a token  it doesn't work ....

**Comment by JoaoDanielRufino** [comment]
I will also try this when I have some time...

In the meantime you could open an issue to go-getter package questioning about the token method

**Comment by colussim** [comment]
I've just found that forcing the protocol by prefixing the url works for example: git::https://TOKEN@github.com/org/repos
